"""Initial migration.

Revision ID: e7a768bcc213
Revises: 
Create Date: 2023-02-16 17:39:22.805842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a768bcc213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('training',
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('training_id')
    )
    op.create_table('training_exercise',
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('training_id', 'exercise_id')
    )
    op.create_table('training_history',
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('training_id', 'user_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('publickey', sa.String(length=128), nullable=True),
    sa.Column('nonce', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('training_history')
    op.drop_table('training_exercise')
    op.drop_table('training')
    op.drop_table('profile')
    op.drop_table('exercise')
    # ### end Alembic commands ###
