"""Initial migration.

Revision ID: ee1883a08368
Revises: 
Create Date: 2023-02-16 17:19:17.514447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1883a08368'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('pofile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('training',
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('training_id')
    )
    op.create_table('training_exercise',
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('training_id', 'exercise_id')
    )
    op.create_table('training_history',
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('training_id', 'user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('password')
        batch_op.drop_column('user_id')

    op.drop_table('training_history')
    op.drop_table('training_exercise')
    op.drop_table('training')
    op.drop_table('pofile')
    op.drop_table('exercise')
    # ### end Alembic commands ###
