export default class BaseMotion {

    parts = {
		Hips: null,
		Spine: null,
		Spine1: null,
		Spine2: null,
		Neck: null,
		Head: null,
		LeftShoulder: null,
		LeftArm: null,
		LeftForeArm: null,
		LeftHand: null,
		LeftHandThumb1: null,
		LeftHandThumb2: null,
		LeftHandThumb3: null,
		LeftHandThumb4: null,
		LeftHandIndex1: null,
		LeftHandIndex2: null,
		LeftHandIndex3: null,
		LeftHandIndex4: null,
		LeftHandMiddle1: null,
		LeftHandMiddle2: null,
		LeftHandMiddle3: null,
		LeftHandMiddle4: null,
		LeftHandRing1: null,
		LeftHandRing2: null,
		LeftHandRing3: null,
		LeftHandRing4: null,
		LeftHandPinky1: null,
		LeftHandPinky2: null,
		LeftHandPinky3: null,
		LeftHandPinky4: null,
		RightShoulder: null,
		RightArm: null,
		RightForeArm: null,
		RightHand: null,
		RightHandThumb1: null,
		RightHandThumb2: null,
		RightHandThumb3: null,
		RightHandThumb4: null,
		RightHandIndex1: null,
		RightHandIndex2: null,
		RightHandIndex3: null,
		RightHandIndex4: null,
		RightHandMiddle1: null,
		RightHandMiddle2: null,
		RightHandMiddle3: null,
		RightHandMiddle4: null,
		RightHandRing1: null,
		RightHandRing2: null,
		RightHandRing3: null,
		RightHandRing4: null,
		RightHandPinky1: null,
		RightHandPinky2: null,
		RightHandPinky3: null,
		RightHandPinky4: null,
		LeftUpLeg: null,
		LeftLeg: null,
		LeftFoot: null,
		RightUpLeg: null,
		RightLeg: null,
		RightFoot: null,
	};
    
    constructor() {
    }
}